In [3]:
import numpy as np
import sympy as sp
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
B = np.array([
    [7,8,9],
    [1,2,3],
    [4,5,6]
])
# การสร้างเมทริกแบบรวม เมทริก [A | B]
print(np.hstack((A, B)))

[[1 2 7 8 9]
 [3 4 1 2 3]
 [5 6 4 5 6]]


In [4]:
A2 = sp.Matrix([
    [1,2],
    [3,4],
    [5,6]
])
B2 = sp.Matrix([
    [7,8,9],
    [1,2,3],
    [4,5,6]
])
#  การสร้างเมทริกแบบ [A | B]
aug = A2.row_join(B2)
sp.pprint(aug)
m , n = A2.shape # m = row, n = columns
sp.pprint(m)
sp.pprint(n)

⎡1  2  7  8  9⎤
⎢             ⎥
⎢3  4  1  2  3⎥
⎢             ⎥
⎣5  6  4  5  6⎦
3
2


In [9]:
matrix_A = sp.Matrix([
    [1, -1],
    [2, 0],
    [3, 4]
])
matrix_B = sp.Matrix([
    [2, 1],
    [0, 3],
    [-1, 5]
])

#การสร้างเมทริกแต่งเติม 
sp.pprint(matrix_A.row_join(matrix_B))


# ระบุ shape ของเมทริกแต่งเติม
row, col = matrix_A.row_join(matrix_B).shape
sp.pprint(row)
sp.pprint(col)

⎡1  -1  2   1⎤
⎢            ⎥
⎢2  0   0   3⎥
⎢            ⎥
⎣3  4   -1  5⎦
3
4


In [24]:
A3 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])

#การเรียกเมทริกย่อย 1:3 เป็นการบอกแถว 2:5 เป็นการบอก columns 
slicing = A3[1:3, 2:5]
print(slicing)
print("Row: ", A3[3, : ])
print("Columns: ", A3[:, 1])
print("Matrix megsent: ", A3[0 : 2] )
print("Matrix megsent: ", A3[3: 4])

[[ 8  9 10]
 [13 14 15]]
Row:  [16 17 18 19 20]
Columns:  [ 2  7 12 17]
Matrix megsent:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Matrix megsent:  [[16 17 18 19 20]]


In [26]:
A4 = sp.Matrix([
    [1,2,-1,0],
    [2,4,-2,1],
    [3,6,0,-1]
])
row1, col1 = A4.rref()

# แสดงข้อมูลเป็น metrix ที่เป็น rref
sp.pprint(row1)

# col1 เป็นการบอกว่า เลข 1 อยู่ตำแหน่งไหนบ้าง
sp.pprint(col1)

⎡1  2  0  0⎤
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦
(0, 2, 3)


In [81]:
A5 = sp.Matrix([
    [2,1],
    [5,3]
])

# n เก็บขนาดของแถวว่ามีขนาดเท่าไร 
n = A5.rows

# สร้างเมทริกเอกลักษณ์
I = sp.eye(n)

# ทำการรวมเมทริกเอกลักษณ์เข้าไปที่ metrix ตัวใหม่
Metrix_A5_I = A5.row_join(I)

# สร้างเมทริกโดยทำให้เป็น rref
row2, col2 = Metrix_A5_I.rref()

# แบบไม่มีการ invert
left = row2[:, :n]

# ทำให้เป็น invert
inv = row2[:, n:]
sp.pprint(row2)

# เช็คว่า เมทริกฝั่งซ้าย || ฝั่งขวา เป็นเอกลักษณ์ หรือไม่
if inv == sp.eye(n):
    print("\n A is invertible and ")
    sp.pprint(inv)

# ถ้าไม่เป็นเอกลักษณ์ 
else: 

    # เอาไปคูณกับเมทริกตัวเดิมได้เลย
    sp.pprint(A5*inv)

⎡1  0  3   -1⎤
⎢            ⎥
⎣0  1  -5  2 ⎦
⎡1  0⎤
⎢    ⎥
⎣0  1⎦


In [82]:
A6 = sp.Matrix([
    [1,2,3, 5],
    [4,5,6, 4],
    [7,8,9, 5],
    [10,11,12,4]
])
n2 = A6.rows
inter = sp.eye(n2)

MM = A6.row_join(inter)
row3, col3 = MM.rref()
left = row3[:, :n2]
inv2 = row3[:, n2:]
sp.pprint(row3)

# เช็คว่าผกผันหรือไม่
if  A6.det() != 0:
    print("Yes")
    sp.pprint(inv2)
else: 
    print("No Invert")

⎡1  0  -1  0  0  -23/6  4   -7/6⎤
⎢                               ⎥
⎢0  1  2   0  0  11/3   -4  4/3 ⎥
⎢                               ⎥
⎢0  0  0   1  0  -1/2   1   -1/2⎥
⎢                               ⎥
⎣0  0  0   0  1   -1    -1   1  ⎦
No Invert


In [83]:
A7 = sp.Matrix([
    [1,2,0],
    [3,4, -1]
])
row, col4 = A7.shape

# กาทำ metrix มูลฐาน
II = sp.eye(row)
agrument = A7.row_join(II)
R, pivots = agrument.rref()


B3 = R[:, :col4]
P = R[:, col4:]
sp.pprint(R)
print("\n")

print("B3: \n")
sp.pprint(B3)
print("\n")

print("P = \n")
sp.pprint(P)

print("PA7 == B3: ", (P*A7).equals(B3))

⎡1  0  -1   -2    1  ⎤
⎢                    ⎥
⎣0  1  1/2  3/2  -1/2⎦


B3: 

⎡1  0  -1 ⎤
⎢         ⎥
⎣0  1  1/2⎦


P = 

⎡-2    1  ⎤
⎢         ⎥
⎣3/2  -1/2⎦
PA7 == B3:  True


In [84]:
A8 = sp.randMatrix(4,3,0,20)


m2, n4 = A8.shape
I3 = sp.eye(m2)
argru2 = A8.row_join(I3)
R2, pivots2 = argru2.rref()

B4 = R2[:, :n4]
P2 = R2[:, n4:]
print(P2.shape)

# เช็คว่าเอา P มาคูณเมทริกหลัก จะได้เท่ากับ ตัวตรงข้ามหรือไม่
print("P2 * A8 == B4", (P2*A8).equals(B4))
print("----------------------------------------------------")


matrix_1 = sp.randMatrix(4, 5, 1, 20)
m3, n5 = matrix_1.shape
I4 = sp.eye(m3)
aug3 = matrix_1.row_join(I4)
R3, pivots3 = aug3.rref()
B5 = R3[:, :n5]
P3 = R3[:, n5:]

print(P3.shape)
print("P3 * matrix_1 == B5", (P2*matrix_1).equals(B5))

(4, 4)
P2 * A8 == B4 True
----------------------------------------------------
(4, 4)
P3 * matrix_1 == B5 False
