In [3]:
import numpy as np
import sympy as sp
A = np.array([
    [3, 1], 
    [5,2]
])
detA = np.linalg.det(A)
print(detA)

1.0000000000000009


In [4]:
two = np.array([
    [1,2,3],
    [2,4,6],
    [-5,0,0.5]
])
print(np.linalg.det(two))

0.0


In [5]:
three = np.array([
    [1,0,2],
    [-1,3,4],
    [2,1,5]
])
print(np.linalg.det(three))

-2.9999999999999996


In [6]:
ran = np.random.randint(0,10, (6,6))
print(ran)

[[2 3 7 8 0 8]
 [7 2 2 8 7 6]
 [5 1 2 2 5 2]
 [4 6 7 3 0 6]
 [9 2 3 4 5 3]
 [9 1 9 7 3 6]]


In [7]:
AA = np.array([
    [2,1,0,0],
    [0,3,4,0],
    [0,0,5,6],
    [0,0,0,7]
])
print(np.linalg.det(AA))
new_A = AA.copy()
new_A[2,3] = 10
print("new_A: ", np.linalg.det(new_A))

209.99999999999994
new_A:  209.99999999999994


In [8]:
metrix_A = np.array([
    [3,1,-1,4],
    [2,0,4,0],
    [1,0.5,3,6],
    [0,-3,0,2]
])
B = metrix_A.copy()
B[[0,1], :] = B[[1,0], :]
print("metrix_A: ",np.linalg.det(metrix_A))
print("metrix_B: ", np.linalg.det(B))
B2 = metrix_A.copy()
B2[[0, 1], :] = B2[[1,0], :]
B2[[2, 3], :] = B2[[3,2], :]
print(np.linalg.det(metrix_A))
print(np.linalg.det(B2))

B = metrix_A.copy()
B[2,:] = -2*B[2,:]
print(np.linalg.det(metrix_A))
print(np.linalg.det(B))

B[3, :] = B[3, :] + 5 * B[0, :]
print(np.linalg.det(metrix_A))
print(np.linalg.det(B))

metrix_A:  -294.0000000000002
metrix_B:  294.0000000000002
-294.0000000000002
-294.0000000000002
-294.0000000000002
588.0000000000005
-294.0000000000002
587.9999999999999


In [9]:
metrix2 = np.array([
    [3,1,-1,4],
    [2,0,4,0],
    [1,0.5,3,6],
    [0,-3,0,2]
])
swap = metrix2.copy()
swap[:, [0,1]] = swap[ :,[1,0]]
print(np.linalg.det(metrix2))
print(np.linalg.det(swap))

swap[:, [0,2]] = swap[:,[2, 0]]
print(np.linalg.det(swap))
swap[:, [2, 3]] = swap[:, [3, 2]]
print(np.linalg.det(swap))
swap[:, 1] = 5 * swap[:, 1]
print(np.linalg.det(swap))
swap[:, 1] = swap[:, 1] - 3 * swap[:, 0]
print(np.linalg.det(swap))

-294.0000000000002
294.0000000000002
-294.0000000000002
293.99999999999994
1470.0000000000011
1470.0000000000011


In [10]:
Aw = np.array([
    [2,1],
    [5,3]
])
print(np.linalg.det(Aw))
if abs(np.linalg.det(Aw)) < 1e-10:
    print("A is not invert")
else:
    Ainv = np.linalg.inv(Aw)
    print(Ainv)
    print(Aw @ Ainv)
    

1.0000000000000009
[[ 3. -1.]
 [-5.  2.]]
[[ 1.00000000e+00  2.22044605e-16]
 [-8.88178420e-16  1.00000000e+00]]


In [11]:
As = sp.Matrix([
    [2,1],
    [5,3]
])
n = As.rows
I = sp.eye(n)

Aug = As.row_join(I)
R, pivot = Aug.rref()
left = R[:, :n]
right = R[:, n:]
sp.pprint(R)
if left == sp.eye(n):
    sp.pprint(right)
else:
    print(As*right)

⎡1  0  3   -1⎤
⎢            ⎥
⎣0  1  -5  2 ⎦
⎡3   -1⎤
⎢      ⎥
⎣-5  2 ⎦


In [13]:
coef = np.array([
    [1,2,-1],
    [2,4, 0],
    [3,-1,5]
])
coef_B = np.array([3,6,1])
print(np.linalg.det(coef))
if not np.isclose(np.linalg.det(coef), 0):
    result = np.linalg.solve(coef, coef_B)
    print(result)
    
else:
    print("is result one ")

14.000000000000004
[ 0.71428571  1.14285714 -0.        ]
