In [2]:
import numpy as np
import sympy as sp
from numpy import linalg as LA
from sympy import *

In [3]:
# ตรวจสอบ vecter ลักษณะเฉพาะที่เป็นอิสระเชิงเส้นต่อกัน
A1 = sp.Matrix([[2,1],[1,2]])
A1.eigenvects()

[(1,
  1,
  [Matrix([
   [-1],
   [ 1]])]),
 (3,
  1,
  [Matrix([
   [1],
   [1]])])]

In [4]:
# ตรวจสอบสมการ Ax = lamda X
for eigval, mult, vects in A1.eigenvects():
    v = vects[0]
    print(eigval, A1 * v, eigval * v, sp.simplify(A1*v - eigval*v))

1 Matrix([[-1], [1]]) Matrix([[-1], [1]]) Matrix([[0], [0]])
3 Matrix([[3], [3]]) Matrix([[3], [3]]) Matrix([[0], [0]])


In [5]:
A2 = sp.Matrix([[4,-2],[1,1]])
A2.eigenvects()

[(2,
  1,
  [Matrix([
   [1],
   [1]])]),
 (3,
  1,
  [Matrix([
   [2],
   [1]])])]

In [6]:
for eigval, mult, vects in A2.eigenvects():
    v = vects[0]
    print(eigval, A2 * v, eigval * v, sp.simplify(A2*v - eigval*v))

2 Matrix([[2], [2]]) Matrix([[2], [2]]) Matrix([[0], [0]])
3 Matrix([[6], [3]]) Matrix([[6], [3]]) Matrix([[0], [0]])


In [7]:
A3 = sp.Matrix([[3,0],[0,3]])
A3.eigenvects()

[(3,
  2,
  [Matrix([
   [1],
   [0]]),
   Matrix([
   [0],
   [1]])])]

In [8]:
for eigval, mult, vects in A3.eigenvects():
    v = vects[0]
    print(eigval, A3 * v, eigval * v, sp.simplify(A3*v - eigval*v))

3 Matrix([[3], [0]]) Matrix([[3], [0]]) Matrix([[0], [0]])


In [9]:
A4 = sp.Matrix([
    [2,1,0],
    [0,2,1],
    [0,0,2]
])
A4.eigenvects()

[(2,
  3,
  [Matrix([
   [1],
   [0],
   [0]])])]

In [10]:
for eigval, mult, vects in A4.eigenvects():
    v = vects[0]
    print(eigval, A4 * v, eigval * v, sp.simplify(A4*v - eigval*v))

2 Matrix([[2], [0], [0]]) Matrix([[2], [0], [0]]) Matrix([[0], [0], [0]])


In [11]:
A5 = np.array([
    [4,0,0],
    [0,4,0],
    [0,0,2]
])
# eig_vec,eig_val = LA.eig(A5)
print(LA.eig(A5))

EigResult(eigenvalues=array([4., 4., 2.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [12]:
eig_val, eig_vec = LA.eig(A5) 

for i in range(len(eig_val)):
    eigval = eig_val[i]
    v = eig_vec[:, i] 
    print(f"Eigenvalue {i+1}: {eigval}")
    print(f"Result (λ*v): {eigval * v}")
    print("-" * 10)

Eigenvalue 1: 4.0
Result (λ*v): [4. 0. 0.]
----------
Eigenvalue 2: 4.0
Result (λ*v): [0. 4. 0.]
----------
Eigenvalue 3: 2.0
Result (λ*v): [0. 0. 2.]
----------


In [13]:
A6 = sp.Matrix([
    [1,0,0,0,2],
    [1,1,0,0,0],
    [0,0,3,0,0],
    [2,0,-2,1,1],
    [0,2,0,0,-2]
])
for eigval, mult, vects in A6.eigenvects():
    v = vects[0]
    print(eigval, A6.eigenvals())

-1 {2: 1, -1: 2, 3: 1, 1: 1}
1 {2: 1, -1: 2, 3: 1, 1: 1}
2 {2: 1, -1: 2, 3: 1, 1: 1}
3 {2: 1, -1: 2, 3: 1, 1: 1}


In [14]:
# แต่ละ i = 1, 2, 3, 4, 5 คำนวนเวกเตอร์ลักษณะเฉพาะ vi ของ A ที่สมนัยกับ λi
eigen_info = A6.eigenvects()
count = 1
for val, mult, vectors in eigen_info:
    for v in vectors:
        print(sp.N(val, 3) ,list(v))
        count+=1

-1.00 [-1, 1/2, 0, 1/2, 1]
1.00 [0, 0, 0, 1, 0]
2.00 [2, 2, 0, 5, 1]
3.00 [0, 0, -1, 1, 0]


In [15]:
# แต่ละ i = 1, 2, 3, 4, 5 คำนวน Avi และ λivi พร้อมวิเคราะห์ว่าสัมพันธ์กันอย่างไร
data = A6.eigenvects()
idx = 1
for lam, mult, vects in data:
    for v in vects:
        print(lam)
        sp.pprint(v)
        idx += 1

-1
⎡-1 ⎤
⎢   ⎥
⎢1/2⎥
⎢   ⎥
⎢ 0 ⎥
⎢   ⎥
⎢1/2⎥
⎢   ⎥
⎣ 1 ⎦
1
⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣0⎦
2
⎡2⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢5⎥
⎢ ⎥
⎣1⎦
3
⎡0 ⎤
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎢-1⎥
⎢  ⎥
⎢1 ⎥
⎢  ⎥
⎣0 ⎦


In [16]:
lamda_A = list(A6.eigenvals().keys())
for k in range(1, 21):
    lam_k = [lam**k for lam in  lamda_A]
    print(lam_k)
    A_pow_k = A6 ** k
    beta = list(A_pow_k.eigenvals().keys())
    print(beta)

[2, -1, 3, 1]
[2, -1, 3, 1]
[4, 1, 9, 1]
[4, 1, 9]
[8, -1, 27, 1]
[8, -1, 27, 1]
[16, 1, 81, 1]
[16, 1, 81]
[32, -1, 243, 1]
[32, -1, 243, 1]
[64, 1, 729, 1]
[64, 1, 729]
[128, -1, 2187, 1]
[128, -1, 2187, 1]
[256, 1, 6561, 1]
[256, 1, 6561]
[512, -1, 19683, 1]
[512, -1, 19683, 1]
[1024, 1, 59049, 1]
[1024, 1, 59049]
[2048, -1, 177147, 1]
[2048, -1, 177147, 1]
[4096, 1, 531441, 1]
[4096, 1, 531441]
[8192, -1, 1594323, 1]
[8192, -1, 1594323, 1]
[16384, 1, 4782969, 1]
[16384, 1, 4782969]
[32768, -1, 14348907, 1]
[32768, -1, 14348907, 1]
[65536, 1, 43046721, 1]
[65536, 1, 43046721]
[131072, -1, 129140163, 1]
[131072, -1, 129140163, 1]
[262144, 1, 387420489, 1]
[262144, 1, 387420489]
[524288, -1, 1162261467, 1]
[524288, -1, 1162261467, 1]
[1048576, 1, 3486784401, 1]
[1048576, 1, 3486784401]


 a และ b เป็นไปตามทฤษฎีบทของการส่งเสปกตรัม

In [17]:
print(A6.det())

6


In [18]:
eigenvals_dict = A6.eigenvals()
product = 1
for val, multiplicity in eigenvals_dict.items():
    product *= (val ** multiplicity)
    print(product)

2
2
6
6


In [19]:
dets = A6.det()
if product == dets:
    print("equals")
else:
    print("not equals")

equals


In [20]:
A7 = np.array([
    [1,0,0,0,2],
    [1,1,0,0,0],
    [0,0,3,0,0],
    [2,0,-2,1,1],
    [0,2,0,0,-2]
])
eig_val, eig_vec = np.linalg.eig(A7)
for i in range(len(eig_val)):
    lam = eig_val[i]
    v = eig_vec[:, i]
    print(lam)

(1+0j)
(1.9999999999999996+0j)
(-0.999999999999999+6.452392069879461e-09j)
(-0.999999999999999-6.452392069879461e-09j)
(3+0j)


In [21]:
for i in range(len(eig_val)):
    lam = eig_val[i]
    v = eig_vec[:, i]
    Avi = np.dot(A7, v)
    lam_vi = lam * v
    print(Avi)
is_equals = np.allclose(Avi, lam_vi)
if is_equals :
    print("equals")
else: 
    print("not equals")

[0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
[0.68599434+0.j 0.68599434+0.j 0.        +0.j 1.71498585+0.j
 0.34299717+0.j]
[ 0.63245553-4.08085106e-09j -0.31622777+1.02021276e-09j
  0.        +0.00000000e+00j -0.31622777+4.13590306e-25j
 -0.63245553+6.12127659e-09j]
[ 0.63245553+4.08085106e-09j -0.31622777-1.02021276e-09j
  0.        +0.00000000e+00j -0.31622777-4.13590306e-25j
 -0.63245553-6.12127659e-09j]
[ 0.        +0.j  0.        +0.j  2.12132034+0.j -2.12132034+0.j
  0.        +0.j]
equals


In [22]:
A_3x3 = np.random.randint(0, 9, (3,3))
vals, Q = np.linalg.eig(A_3x3)
L = np.diag(vals)
Q_inv = np.linalg.inv(Q)
result = Q @ L @ Q_inv
print(np.round(L, 2), "\n")
print(np.round(Q, 2), "\n")
print(np.round(result.real, 0))

[[14.32+0.j   0.  +0.j   0.  +0.j ]
 [ 0.  +0.j  -1.66+2.4j  0.  +0.j ]
 [ 0.  +0.j   0.  +0.j  -1.66-2.4j]] 

[[-0.45+0.j   -0.35+0.3j  -0.35-0.3j ]
 [-0.32+0.j    0.77+0.j    0.77-0.j  ]
 [-0.83+0.j   -0.35-0.27j -0.35+0.27j]] 

[[1. 3. 6.]
 [7. 2. 1.]
 [6. 8. 8.]]


In [23]:
for n_size in [4, 5]:
    A_gen = np.random.randint(0,10, size=(n_size, n_size)) # สุ่มเมทริกซ์
    
    vals_gen, Q_gen = np.linalg.eig(A_gen)
    L_gen = np.diag(vals_gen)
    Q_inv_gen = np.linalg.inv(Q_gen)
    
    Result_gen = Q_gen @ L_gen @ Q_inv_gen

print("Result: ", Result_gen)

Result:  [[ 1.00000000e+00+6.28750700e-17j  8.00000000e+00+1.59634036e-17j
   5.00000000e+00+2.53741179e-16j  6.00000000e+00+1.71418184e-15j
   5.00000000e+00-5.70964765e-17j]
 [ 9.00000000e+00-1.97239386e-16j  9.00000000e+00-1.36606083e-16j
   8.00000000e+00+1.29937241e-15j  2.00000000e+00+2.28090079e-15j
   7.00000000e+00+3.60547912e-16j]
 [ 7.00000000e+00-3.26428995e-16j  4.00000000e+00-1.81968701e-16j
   9.00000000e+00+1.02326135e-15j  3.00000000e+00+2.47658083e-15j
   9.00000000e+00+1.75509320e-16j]
 [ 3.00000000e+00+4.72459374e-16j  9.00000000e+00+3.27847080e-16j
  -2.66453526e-15-1.88044227e-16j  8.00000000e+00+7.06882767e-16j
   3.00000000e+00-3.93587948e-16j]
 [ 2.00000000e+00+2.23644078e-16j  8.00000000e+00+9.42745744e-17j
   3.00000000e+00+5.78504626e-19j  7.00000000e+00+1.23774828e-15j
   2.00000000e+00-1.75760259e-16j]]
