In [8]:
import numpy as np
me = np.random.randint(0, 9, (3,5))
print(me)
print(me[1,:4])
print(me[0,:])
print(me[:,4])

[[6 5 6 6 1]
 [5 3 2 5 3]
 [2 8 8 4 3]]
[5 3 2 5]
[6 5 6 6 1]
[1 3 3]


In [9]:
list1 = [0,1,2,3,4,5]
list2 = [2,4,6,8,10]
list3 = [10,9,8,7,6]
print(list1, list2, list3)

[0, 1, 2, 3, 4, 5] [2, 4, 6, 8, 10] [10, 9, 8, 7, 6]


In [13]:
zero = np.zeros((3,4))
one = np.ones((4,4))
iden = np.identity(4)
print(zero)
print(one)
print(iden)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
tayang = np.diag([3,5,7])
print(tayang)

[[3 0 0]
 [0 5 0]
 [0 0 7]]


In [16]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
C = A+B
print(C)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [18]:
a = np.random.randint(0, 9,(4,3))
print(3 * a)
print("\n")
print(-2 * a)

[[ 6 15  6]
 [24 12  6]
 [12 18 18]
 [ 9  0 24]]


[[ -4 -10  -4]
 [-16  -8  -4]
 [ -8 -12 -12]
 [ -6   0 -16]]


In [23]:
aa = np.random.randint(0,9, (3,4))
bb = np.random.randint(0,9, (4,5))
mul = aa @ bb
print(mul)
print(mul.shape)
print(mul.shape[0])
print(mul.shape[1])

[[27 45 31 38 21]
 [58 87 78 80 45]
 [43 54 62 49 57]]
(3, 5)
3
5


In [29]:
aaa = np.random.randint(0,9, (3,5))
# aaa = np.tranpose(aaa)
print(aaa)
print(np.transpose(aaa))

[[2 7 0 1 4]
 [0 4 4 2 4]
 [7 8 8 4 1]]
[[2 0 7]
 [7 4 8]
 [0 4 8]
 [1 2 4]
 [4 4 1]]


In [30]:
under = np.random.randint(0,9, (4,4))
print(np.tril(under))

[[4 0 0 0]
 [3 0 0 0]
 [6 0 1 0]
 [7 5 6 5]]


In [31]:
expo = np.random.randint(0,9, (3,4))
print(expo ** 2)
print("\n")
print(expo ** 3)

[[64 16 64  0]
 [64 36 16 49]
 [ 9 64 36 16]]


[[512  64 512   0]
 [512 216  64 343]
 [ 27 512 216  64]]


In [34]:
a4 = np.random.randint(0,9, (3,3))
b4 = np.random.randint(0,9, (3,3)) 
A_plus_B = a4 + b4
print(np.transpose(A_plus_B))
print("\n")
print(np.transpose(a4))
print("\n")
print(np.transpose(b4))

[[ 7 13  2]
 [13 12  6]
 [ 8  9  9]]


[[1 8 2]
 [6 5 0]
 [7 1 2]]


[[6 5 0]
 [7 7 6]
 [1 8 7]]


In [35]:
a5 = np.random.randint(0,9, (4,4))
b5 = a5 + np.transpose(a5)
print(b5)

[[14  5 12 10]
 [ 5 10 12  2]
 [12 12 16  7]
 [10  2  7  0]]
