# ปฏิบัติการที่ 3: ดีเทอร์มิแนนต์และตัวผกผันของเมทริกซ์

**วัตถุประสงค์**
- คำนวณดีเทอร์มิแนนต์ของเมทริกซ์จัตุรัส
- ศึกษาผลของการดำเนินการตามแถว/คอลัมน์ต่อดีเทอร์มิแนนต์
- หาเมทริกซ์ผกผัน
- แก้ระบบสมการเชิงเส้นด้วยเมทริกซ์
- ใช้ `numpy` เป็นหลัก (มี remark `sympy` ตอนท้าย)


## การคำนวณดีเทอร์มิแนนต์ด้วย numpy

In [9]:
import numpy as np

A = np.array([[3,1],[5,2]])
print("det(A) =", np.linalg.det(A))

det(A) = 1.0000000000000009


### เฉลยแบบฝึกหัด 3.1

In [14]:
# ข้อ 1
A1 = np.array([[3,1],[5,2]])
print("A1=",A1) 
print("det (A1)=", np.linalg.det(A1))

# ข้อ 2
A2 = np.array([[1,2,3],[2,4,6],[-5,0,0.5]])
print("\nA2=",A2) 
print("det (A2)=", np.linalg.det(A2))

# ข้อ 3
A3 = np.array([[1,0,2],[-1,3,4],[2,1,5]])
print("\nA3=",A3) 
print("det(A3) =", np.linalg.det(A3))

# ข้อ 4: random 6x6
A4 = np.random.randint(0,10, (6,6))
print("\nA4=",A4) 
print("det (A4)=", np.linalg.det(A4))

# ข้อ 5
A5 = np.array([[2,1,0,0],
               [0,3,4,0],
               [0,0,5,6],
               [0,0,0,7]])
print("\nA5=",A5) 
print("det(A) =", np.linalg.det(A5))

A5_1 = A5.copy()
A5_1[0,1] = 10
print("\nA5_1=",A5_1) 
print("det after changing a12 =", np.linalg.det(A5_1))

A5_2 = A5.copy()
A5_2[3,3] = 11
print("\nA5_2=",A5_2)
print("det after changing a44 =", np.linalg.det(A5_2))

A1= [[3 1]
 [5 2]]
det (A1)= 1.0000000000000009

A2= [[ 1.   2.   3. ]
 [ 2.   4.   6. ]
 [-5.   0.   0.5]]
det (A2)= 0.0

A3= [[ 1  0  2]
 [-1  3  4]
 [ 2  1  5]]
det(A3) = -2.9999999999999996

A4= [[7 7 3 5 1 3]
 [1 0 9 8 7 9]
 [5 1 8 8 9 1]
 [2 1 1 0 6 7]
 [3 5 1 7 5 0]
 [0 6 2 3 3 4]]
det (A4)= 116219.99999999993

A5= [[2 1 0 0]
 [0 3 4 0]
 [0 0 5 6]
 [0 0 0 7]]
det(A) = 209.99999999999994

A5_1= [[ 2 10  0  0]
 [ 0  3  4  0]
 [ 0  0  5  6]
 [ 0  0  0  7]]
det after changing a12 = 209.99999999999994

A5_2= [[ 2  1  0  0]
 [ 0  3  4  0]
 [ 0  0  5  6]
 [ 0  0  0 11]]
det after changing a44 = 329.99999999999994


## แบบฝึกหัด 3.2 ผลของการดำเนินการตามแถวต่อดีเทอร์มิแนนต์

In [17]:
A = np.array([[3,1,-1,4],
              [2,0,4,0],
              [1,0.5,3,6],
              [0,-3,0,2]], dtype=float)

detA = np.linalg.det(A)
print("A =",A)
print("det(A)=",detA)

# swap row 1 and 2
B = A.copy()
B[[0,1],:] = B[[1,0],:]
print("\nB =",B)
print("det after swap =", np.linalg.det(B))

# scale row 3 by -2
B = A.copy()
B[2,:] *= -2
print("\nB =",B)
print("det after scaling row 3 =", np.linalg.det(B))

# R4 + 5R1 -> R4
B = A.copy()
B[3,:] += 5*B[0,:]
print("\nB =",B)
print("det after row add =", np.linalg.det(B))

A = [[ 3.   1.  -1.   4. ]
 [ 2.   0.   4.   0. ]
 [ 1.   0.5  3.   6. ]
 [ 0.  -3.   0.   2. ]]
det(A)= -294.0000000000002

B = [[ 2.   0.   4.   0. ]
 [ 3.   1.  -1.   4. ]
 [ 1.   0.5  3.   6. ]
 [ 0.  -3.   0.   2. ]]
det after swap = 294.0000000000002

B = [[  3.   1.  -1.   4.]
 [  2.   0.   4.   0.]
 [ -2.  -1.  -6. -12.]
 [  0.  -3.   0.   2.]]
det after scaling row 3 = 588.0000000000005

B = [[ 3.   1.  -1.   4. ]
 [ 2.   0.   4.   0. ]
 [ 1.   0.5  3.   6. ]
 [15.   2.  -5.  22. ]]
det after row add = -293.99999999999994


##  แบบฝึกหัด 3.3 ผลของการดำเนินการตามคอลัมน์ต่อดีเทอร์มิแนนต์

In [19]:
# swap columns 2 and 3
B = A.copy()
B[:,[1,2]] = B[:,[2,1]]
print("\nB =",B)
print("det after column swap =", np.linalg.det(B))

# swap columns 1 and 3// swap columns 3 and 4
B = A.copy()
B[:,[0,2]] = B[:,[2,0]]
B[:,[2,3]] = B[:,[3,2]]
print("\nB =",B)
print("det after column swap =", np.linalg.det(B))

# scale column 2 by 5
B = A.copy()
B[:,1] *= 5 #  B[:,1] = 5*B[:,1]
print("\nB =",B)
print("det after column scale =", np.linalg.det(B))

# C2 - 3C1 -> C2
B = A.copy()
B[:,1] = B[:,1] - 3*B[:,0]
print("\nB =",B)
print("det after column add =", np.linalg.det(B))


B = [[ 3.  -1.   1.   4. ]
 [ 2.   4.   0.   0. ]
 [ 1.   3.   0.5  6. ]
 [ 0.   0.  -3.   2. ]]
det after column swap = 294.0000000000002

B = [[-1.   1.   4.   3. ]
 [ 4.   0.   0.   2. ]
 [ 3.   0.5  6.   1. ]
 [ 0.  -3.   2.   0. ]]
det after column swap = -293.99999999999994

B = [[  3.    5.   -1.    4. ]
 [  2.    0.    4.    0. ]
 [  1.    2.5   3.    6. ]
 [  0.  -15.    0.    2. ]]
det after column scale = -1470.0

B = [[ 3.  -8.  -1.   4. ]
 [ 2.  -6.   4.   0. ]
 [ 1.  -2.5  3.   6. ]
 [ 0.  -3.   0.   2. ]]
det after column add = -294.0000000000002


## แบบฝึกหัด 3.4 ดีเทอร์มิแนนต์และตัวผกผันของเมทริกซ์

In [32]:
A = np.array([[2,1],[5,3]], dtype=float)
detA = np.linalg.det(A)
print("A =", A)
print("det(A) =", detA)

if abs(detA) < 1e-10:
    print("\nA is not invertible")
else:
    Ainv = np.linalg.inv(A)
    print("\nA^{-1} =\n", Ainv)
    print("\nA @ A^{-1} =\n", A @ Ainv)
    print("\nA*A^{-1} =I_2 (รวม error):", np.array_equal(A@Ainv,np.eye(2))) # มีการเก็บข้อผิดพลาดในตำแหน่งทศนิยมไกล ๆ
    print("\nA*A^{-1} =I_2:", np.allclose(A@Ainv,np.eye(2)))   #

A = [[2. 1.]
 [5. 3.]]
det(A) = 1.0000000000000009

A^{-1} =
 [[ 3. -1.]
 [-5.  2.]]

A @ A^{-1} =
 [[ 1.00000000e+00  2.22044605e-16]
 [-8.88178420e-16  1.00000000e+00]]

A*A^{-1} =I_2 (รวม error): False

A*A^{-1} =I_2: True


In [33]:
A = np.array([[2,3],[4,6]], dtype=float)
detA = np.linalg.det(A)
print("A =", A)
print("det(A) =", detA)

if abs(detA) < 1e-10:
    print("\nA is not invertible")
else:
    Ainv = np.linalg.inv(A)
    print("\nA^{-1} =\n", Ainv)
    print("\nA @ A^{-1} =\n", A @ Ainv)
    print("\nA*A^{-1} =I_2 (รวม error):", np.array_equal(A@Ainv,np.eye(2))) # มีการเก็บข้อผิดพลาดในตำแหน่งทศนิยมไกล ๆ
    print("\nA*A^{-1} =I_2:", np.allclose(A@Ainv,np.eye(2)))   #

A = [[2. 3.]
 [4. 6.]]
det(A) = 0.0

A is not invertible


## แบบฝึกหัด 3.5 ดีเทอร์มิแนนต์กับระบบสมการเชิงเส้น
  พิจารณาระบบสมการ
$
    	\begin{cases}
    		x+2y-z=3\\
    		2x+4y=6\\
    		3x-y+5z=1
    	\end{cases}
$

In [35]:
A = np.array([[1,1,1],
              [2,-1,3],
              [3,2,-1]], dtype=float)
B = np.array([[6],[14],[5]], dtype=float)

print("A =", A)
print("B =", B)

detA = np.linalg.det(A)
print("det(A) =", detA)

if abs(detA) < 1e-10:
    print("No unique solution")
else:
    X = np.linalg.inv(A) @ B
    print("Solution X =", X)

A = [[ 1.  1.  1.]
 [ 2. -1.  3.]
 [ 3.  2. -1.]]
B = [[ 6.]
 [14.]
 [ 5.]]
det(A) = 13.0
Solution X = [[2.46153846]
 [0.38461538]
 [3.15384615]]


## แบบฝึกหัด (พร้อมเฉลย)

In [44]:
# Determinant powers
A = np.array([[1,-1,0],[5,0,-2],[-2,3,0.5]])
print("A =", A)
print("det(A) =", np.linalg.det(A))
print("det(A^2) =", np.linalg.det(A@A))
print("det(A^10) =", np.linalg.det(np.linalg.matrix_power(A,10)))

# Check invertibility
detA = np.linalg.det(A)
if abs(detA) < 1e-10:
    print("\nA not invertible")
else:
    Ainv=np.linalg.inv(A)
    print("\nA inverse =\n", Ainv)
    print("\nA * A^{-1} =\n", A @ Ainv)
    print("\nA*A^{-1} =I_3:", np.allclose(A@Ainv,np.eye(3)))   #

# Linear system
A = np.array([[2,1,-3],[1,-2,1],[1,-1,5]], dtype=float)
B = np.array([[1],[0],[2]], dtype=float)

print("A =", A)
print("B =", B) 

print("det(A) =", np.linalg.det(A))
if abs(np.linalg.det(A)) < 1e-10:
    print("\nNo unique solution")
else:
    print("\nSolution =", np.linalg.inv(A) @ B)

# Linear system
A = np.array([[2,1,-3],[1,-2,1],[3,-1,-2]], dtype=float)
B = np.array([[1],[4],[5]], dtype=float)

print("A =", A)
print("B =", B) 

print("det(A) =", np.linalg.det(A))
if abs(np.linalg.det(A)) < 1e-10:
    print("\nNo unique solution")
else:
    print("\nSolution =", np.linalg.inv(A) @ B)

A = [[ 1.  -1.   0. ]
 [ 5.   0.  -2. ]
 [-2.   3.   0.5]]
det(A) = 4.5
det(A^2) = 20.250000000000004
det(A^10) = 3405062.9280207623

A inverse =
 [[ 1.33333333  0.11111111  0.44444444]
 [ 0.33333333  0.11111111  0.44444444]
 [ 3.33333333 -0.22222222  1.11111111]]

A * A^{-1} =
 [[1.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]

A*A^{-1} =I_3: True
A = [[ 2.  1. -3.]
 [ 1. -2.  1.]
 [ 1. -1.  5.]]
B = [[1.]
 [0.]
 [2.]]
det(A) = -25.000000000000007

Solution = [[0.76]
 [0.56]
 [0.36]]
A = [[ 2.  1. -3.]
 [ 1. -2.  1.]
 [ 3. -1. -2.]]
B = [[1.]
 [4.]
 [5.]]
det(A) = -2.2204460492503135e-15

No unique solution
